pymc-devs/pymc-data-umbrella

sprint/docstring_tutorial.md
sprint/index.md
webinars/contributing_to_documentation/index.md
webinars/table_of_events.md

some updates to pre/post/docstring tutorial

---

about/intuitive_modeling/index.md

adding Oriol video description

---

about/example_pr/index.md

add video and details for Reshama example PR

---

2022-07_sprint/index.md
2022-07_sprint/schedule.md
2022-07_sprint/schedule_table.md
2022-07_sprint/sprint_parties/community_partners.md
_html/robots.txt
_html/sitemap-index.xml
conf.py
index.md
requirements-docs.txt

- Closes #79
- referencing text from AFME2 scikit-learn sprint here:  https://afme2021rc.dataumbrella.org/community-partners

update homepage, navbar, conf and add how to become a community partner text

---

about/contributing_to_pymc/index.md

text for Ricardo talk: clean up

---

2022-07_sprint/sprint_parties/community_partners.md
contributing/donate.md
contributing/index.md

It improves the contribute section.

Contribute section

---

2022-07_sprint/schedule_table.part.md
sprint/faq.md

Answering a question received by email:
>Do we need to attend all the sessions?
Add a clarification on the schedule page.

FAQ: attend all sessions?

---

2022-07_sprint/sprint_parties/contributors.md

Trying this again.  Hopefully it works better than last time!

Adding single contributor

---

2022-07_sprint/sprint_parties/community_partners.md
2022-07_sprint/sprint_parties/media_kit.md

How does this look @reshamas ? closes #110

add button for social media kit

---

2022-07_sprint/sprint_parties/contributors.md

Almost all the remaining contributors.

Adding additional contributors

---

2022-07_sprint/sprint_parties/contributors.md

FYI, I am just adding all the text info and skipping over the pictures.  I figure those can be done separately (especially given that we missing some images).

Adding more contributors

---

2022-07_sprint/sprint_parties/contributors.md

I've added my headshot. Thank you, @reshamas, for the reminder.

Add headshot for Zoe Braiterman

---

2022-07_sprint/sprint_parties/contributors.md

Added contributor info,
Thank you ! @reshamas

Contributor info

---

2022-07_sprint/sprint_parties/contributors.md

@reshamas 
This PR adds Margaret Okore’s profile to the list of contributors.

feat : add margaret okore profile

---

about/contributing_to_documentation/docs_presentation.md

It fixes #141 
It adds titles to the cards to show the version.

Update link and label cards

---

2022-07_sprint/sprint_parties/media_kit.md

#140 is the issue.
Please review :)

Fixed table markdown

---

.github/workflows/tx-pull.yml

Add manual trigger to txpull job

Add manual trigger

---

.github/workflows/tx-pull.yml

I have done multiple tests, and this should fix the txpull job,
as shown by the eventually working #163 PR.

Fix txpull action

---

conf.py

Increase header links

---

.github/config.yml

Towards: https://github.com/pymc-devs/pymc-data-umbrella/issues/191
Welcome bot added with updated links of - 
1. CONTRIBUTING.md
2. CODE_OF_CONDUCT.md

Welcome Bot added with updated links

---

2023-03_sprint/index.md
2023-03_sprint/sprint_parties/sponsors.md

:books: Documentation preview en :books:: https://pymc-data-umbrella--203.org.readthedocs.build/en/203/
:books: Documentation preview es :books:: https://pymc-data-umbrella-es--203.org.readthedocs.build/es/203/
:books: Documentation preview pt :books:: https://pymc-data-umbrella-pt--203.org.readthedocs.build/pt/203/

add Mariatta video on Sponsor page

---

2023-03_sprint/sprint_parties/media_kit.md

:books: Documentation preview en :books:: https://pymc-data-umbrella--205.org.readthedocs.build/en/205/
:books: Documentation preview es :books:: https://pymc-data-umbrella-es--205.org.readthedocs.build/es/205/
:books: Documentation preview pt :books:: https://pymc-data-umbrella-pt--205.org.readthedocs.build/pt/205/

add twitter+LI announcement links for Mar 2023 event

---

contributing/index.md
contributing/issues_list.md

:books: Documentation preview en :books:: https://pymc-data-umbrella--214.org.readthedocs.build/en/214/
:books: Documentation preview es :books:: https://pymc-data-umbrella-es--214.org.readthedocs.build/es/214/
:books: Documentation preview pt :books:: https://pymc-data-umbrella-pt--214.org.readthedocs.build/pt/214/

add link to issues list

---

contributing/issues_list.md

References #214 
:books: Documentation preview en :books:: https://pymc-data-umbrella--215.org.readthedocs.build/en/215/
:books: Documentation preview es :books:: https://pymc-data-umbrella-es--215.org.readthedocs.build/es/215/
:books: Documentation preview pt :books:: https://pymc-data-umbrella-pt--215.org.readthedocs.build/pt/215/

add sphinx refs

---

2023-03_sprint/sprint_parties/contributors.md

:books: Documentation preview en :books:: https://pymc-data-umbrella--223.org.readthedocs.build/en/223/
:books: Documentation preview es :books:: https://pymc-data-umbrella-es--223.org.readthedocs.build/es/223/
:books: Documentation preview pt :books:: https://pymc-data-umbrella-pt--223.org.readthedocs.build/pt/223/

Sai's Profile Addition for sprint 2023_03

---

2023-03_sprint/sprint_parties/contributors.md

#DataUmbrellaPyMCSprint
:books: Documentation preview en :books:: https://pymc-data-umbrella--224.org.readthedocs.build/en/224/
:books: Documentation preview es :books:: https://pymc-data-umbrella-es--224.org.readthedocs.build/es/224/
:books: Documentation preview pt :books:: https://pymc-data-umbrella-pt--224.org.readthedocs.build/pt/224/

Add details to contributors list
